-- Delivery zones (allow-list) for manual/local delivery
create table if not exists delivery_zones (
  id bigint generated by default as identity primary key,
  country text not null,
  city text null,
  postal_code text null,
  phase_label text null,
  conditional numeric null,
  min_order_amount numeric null,
  delivery_fee numeric null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists delivery_zones_country_idx on delivery_zones (country);
create index if not exists delivery_zones_city_idx on delivery_zones (city);
create index if not exists delivery_zones_postal_idx on delivery_zones (postal_code);
