-- Guest order OTPs for email-only verification
create table if not exists guest_order_otps (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  attempts int not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists guest_order_otps_email_idx on guest_order_otps (email);
