create table if not exists special_category_labels (
  id bigint generated by default as identity primary key,
  category_id bigint not null,
  name text not null,
  color text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists special_products
  add column if not exists label_id bigint null;
